### ISSUE TITLE
Share source folder at /vagrant

### ISSUE THREAD

**Issue by ndarilek** [rancher/os-vagrant#10]
It'd be nice if you shipped the necessary NFS modules and VM tools in these images so the source folder can be mounted at /vagrant. I develop with Docker on Windows, and my current painful setup involves using `vagrant rsync-auto` to send the directory up to CoreOS, which is too minimal to ship the NFS modules/VM tools. Maybe they can be packaged in a vagrant-compat addon or something?

**Comment by cloudnautique** [comment]
We agree the rsync only method is a bit of a stop gap. We have plans to get the VBox tools in there once we work out a good system for handling DKMS in RancherOS.

If you are using CoreOS from the Rancher Vagrantfile to run Rancher, I am pretty sure CoreOS has the NFS capability. You just need to add it.

**Comment by ndarilek** [comment]
Right, sorry, it does do NFS. It's Windows that doesn't. Still though,
it'd be nice if Rancher could share /vagrant using the vbox-tools, or
whatever mechanism most stock Vagrant boxes use.

**Comment by ailispaw** [comment]
@cloudnautique
I tried to build a box supporting VirtualBox Shared Folder.
https://github.com/ailispaw/rancheros-lite/tree/vboxsf
https://github.com/ailispaw/os-base/tree/glibc
It seems to need just GLIBC in the RancherOS Base to execute mount.vboxsf.
It works good so far.
https://atlas.hashicorp.com/ailispaw/boxes/rancheros-lite

**Comment by miztiik** [comment]
@ailispaw , Did you manage to get Virtualbox shared folders working with RancherOS ?

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
