### ISSUE TITLE
bzip2 missing

### ISSUE THREAD

**Issue by digitalkaoz** [rancher/os-vagrant#11]
during install i get the following

```
VirtualBox Guest Additions installer
Please install the bzip2 utility.
Copying additional installer modules ...
./install.sh: line 344: bzip2: command not found
tar: short read
./install.sh: line 357: bzip2: command not found
tar: short read
An error occurred during installation of VirtualBox Guest Additions 4.3.26. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
```

but bzip2 is installed :

```
$ bzip2 --version
bzip2, a block-sorting file compressor.  Version 1.0.6, 6-Sept-2010.
```

im on OSX yosemite, vagrant and virtualbox are the newest version.

do i need to install gnu-bzip2?

**Comment by hectorcanto** [comment]
I've experienced a similar issue (I don't have bzip2 installed) with other scenario:
* vagrant 1.7.2 
* virtualbox 4.3.30r101610
* CentOS 7 as guess

To get round pass this issue I've needed to clean the failed installation, install bzip2 and re-run the Guest Additions installation, more or less like this:
```
rm -rf /opt/VBoxGuestAdditions*
sudo yum -y install bzip2
exit
vagrant vbguest
```

I believe the _bzip2_ dependency is missing, some OS might have it pre-installed and others don't.

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
