### ISSUE TITLE
awk in guest plugin

### ISSUE THREAD

**Issue by barm4ley** [rancher/os-vagrant#14]
Hi. Guest plugin doesn't work for me because of -e flag of awk. Without it everything is ok. BR Max.

**Comment by cloudnautique** [comment]
@barm4ley which console are you running in?

**Comment by barm4ley** [comment]
@cloudnautique My host os is OSX Yosemite v. 10.10.2. awk version 20070501.

**Comment by cloudnautique** [comment]
@barm4ley I am unable to reproduce. My understanding, and it may be wrong :), is that the plugin runs inside the guest VM over SSH and not on the host. 

Which box version of Rancher OS are you running? Which console container?

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
