### ISSUE TITLE
multi node mode

### ISSUE THREAD

**Issue by barm4ley** [rancher/os-vagrant#15]
When starting several nodes first time it is always a timeout and only one node is started.
My solution:
```ruby
config.vm.boot_timeout = 400 * $number_of_nodes
```

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
