### ISSUE TITLE
can't start on Mac OSX

### ISSUE THREAD

**Issue by maslick** [rancher/os-vagrant#16]
This is what I get while trying to run ```vagrant up```

![screen shot 2015-04-25 at 10 17 36](https://cloud.githubusercontent.com/assets/5644706/7332205/87ebd984-eb34-11e4-9aab-07691f610cf7.png)

OS: Mac OSX 10.10.3
Vagrant: 1.7.2
VirtualBox: 4.3.26

**Comment by deniseschannon** [comment]
It should work but it just takes longer than before as we have enabled the Ubuntu console. During the boot up, it's downloading the Ubuntu console. Please see #13 for more details.

We are looking into options to see what else could be done to prevent the confusion on success. If your vm is still up, try to ssh in now. It should work.

**Comment by maslick** [comment]
The VM is stuck at ```IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready```
```vagrant ssh``` results in ```ssh_exchange_identification: Connection closed by remote host```

**Comment by jackwilsdon** [comment]
:+1: Having the same issue. Left it for about 5 minutes and I'm still stuck on the same as @maslick.

**Comment by cloudnautique** [comment]
@jackwilsdon, we have it downloading the Ubuntu console because people found the busybox console to be difficult to work in. We have an update in a future release where that image will be prestaged, so it should reduce boot up time.

**Comment by jackwilsdon** [comment]
@cloudnautique Sounds good. Would it be possible to output that it's currently downloading the console? It just looks like it's hung (and googling `docker0: link is not ready` gives you some answers that are not related).

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
