### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ebuildy** [rancher/os-vagrant#18]
Sorry for the silly question, but I can run it fine on Mac OS, but Docker is not accessible from outside :-(

What the good practice to use it?

Thanks,

**Comment by deniseschannon** [comment]
I'm not exactly sure what you are asking. If you follow the directions of the README, after you `vagrant ssh`, you will be inside RancherOS and can start using RancherOS. Inside RancherOS, you can run Docker commands.  

Docker commands will only work if you are inside RancherOS.

**Comment by ebuildy** [comment]
Ha ok, my bad.

How can I access Docker API from outside or how can I install docker-compose ?

Thanks,

**Comment by imikushin** [comment]
@ebuildy if you want to launch a RancherOS VM and access its docker daemon from the outside, there's a more straightforward way to achieve this: use docker-machine, not vagrant.

Here's a really quick Getting Started:

1. Download latest docker-machine:  
`curl -L https://github.com/docker/machine/releases/download/v0.3.0-rc2/docker-machine_darwin-amd64 > ./docker-machine && chmod +x ./docker-machine`
2. Create a RancherOS machine with VirtualBox:  
`./docker-machine create --driver virtualbox --virtualbox-boot2docker-url 'https://github.com/rancherio/os/releases/download/v0.3.1/machine-rancheros.iso' ros-0.3.1`
3. Export the necessary environment for the docker CLI to access Docker API exposed by our new machine:  
`docker-machine env ros-0.3.1  # just to view the env vars`  
`eval "$(docker-machine env ros-0.3.1)"`

Here you are! Now you can use Docker API exposed by RancherOS. 
Type `docker info`
The output should be something like
```
Containers: 0
Images: 0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.3-rancher
Operating System: <unknown>
CPUs: 1
Total Memory: 999.5 MiB
Name: ros-0.3.1
ID: YHJM:HIJV:WTQO:SQPZ:CNFG:JYI2:7PE4:QUGS:OVFM:QQAV:2GRX:5PWM
Username: imikushin
Registry: [https://index.docker.io/v1/]
Labels:
 provider=virtualbox
```
