### ISSUE TITLE
RancherOS configuration via rancher.yml

### ISSUE THREAD

**Issue by pjean** [rancher/os-vagrant#20]
It will be great to have a RancherOS vagrant plugin which allow to configure RancherOS via a rancher.yml.

**Comment by cedvan** [comment]
:+1:

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
