### ISSUE TITLE
RancherOS behind corp http proxy server in Vagrant

### ISSUE THREAD

**Issue by SydOps** [rancher/os-vagrant#27]
Raise the ticket in https://github.com/tmatilai/vagrant-proxyconf/issues/139 to `vagrant-proxyconf` plugin when I set proxy with that plugin, failed

Maybe you have some other ways to share, and know how to set proxy in RanchOS to be able to run "docker pull" behind corporate proxy server.

**Comment by SydOps** [comment]
I manually set system environment http_proxy in RancherOS, still has same issue

**Comment by stefanchiriac** [comment]
any news related to this issue?

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
