### ISSUE TITLE
VMWare provider?

### ISSUE THREAD

**Issue by RVN-BR** [rancher/os-vagrant#29]
Any plans to support a box for the vmware provider?  I'm interested in doing testing with multiple machines and the performance benefits attract me...

thanks!

**Comment by vikas027** [comment]
@RVN-BR You can use [vagrant vshpere-plugin](https://github.com/nsidc/vagrant-vsphere). It works pretty good.

**Comment by RVN-BR** [comment]
Hi @vikas027 , thks for the help, but I was actually looking for the vmware provider (to use on development with fusion instead of vbox)... :+1:

**Comment by vikas027** [comment]
@RVN-BR The link I gave in my earlier post was of the vsphere (VMware ESXi) plugin, not virtualbox. If you are looking for VMware Fusions, then I believe [this](https://www.vagrantup.com/docs/vmware/installation.html) is what you are looking for.

**Comment by RVN-BR** [comment]
Hi @vikas027 I already have the driver, what I was asking for is a RancherOS premade image compatible with the vagrant provider...  At the time I tried it there were only vbox images available...

(different drivers are unfortunately not compatible with a single box... kinda defeats the purpose imho but whatever...)

**Comment by vikas027** [comment]
Aah, got you know @RVN-BR . My apologies, I misunderstood your question. I have not tried RancherOS on VMware ESXi/Fusion yet, but that is my next goal.

**Comment by RVN-BR** [comment]
No worries ;)

If you do get a rancher box for vmware do let me know... I'd like to give it a try to compare fusion and virtualbox...

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
