### ISSUE TITLE
Public IP with bridge mode

### ISSUE THREAD

**Issue by cedvan** [rancher/os-vagrant#31]
Please, add option to declare static ip public to LAN network

**Comment by mbrmj** [comment]
@cedvan  can you tell me how did resolve this probleme? if you happen to know a solution to it.

**Comment by cedvan** [comment]
Hi @mbrmj, I switched to proxmox :wink:

**Comment by mbrmj** [comment]
Hi @cedvan .Thank you for responding , I see that proxmox is an OS, I work on a machine running under ubuntu and I need to setup a virtual "rancher-os" for testing purposes, having to install a whole OS does not suit my need sadly.
