### ISSUE TITLE
Support for the "Vagrant Libvirt Provider"

### ISSUE THREAD

**Issue by kk-klose** [rancher/os-vagrant#32]
**At the moment you get...**

"An error occurred while executing the action on the 'rancher-01'
machine. Please handle this error then try again:

The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it."

**...when you change the provider to libvirt.**

This would be helpful for test environments were is no "Virtual Box".

Thanks!!!

**Comment by kk-klose** [comment]
The provider link:
https://github.com/pradels/vagrant-libvirt

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
